(() => {
  const api=(window.APP_CONFIG||{}).API_URL||""; const $=id=>document.getElementById(id); let secret=""; let dataset=[];
  function msg(text,cls=""){ $("msg").textContent=text; $("msg").className=`msg ${cls}`; }
  async function post(payload){ const r=await fetch(api,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)}); return await r.json(); }
  async function load(){ const r=await post({action:"adminList",secret}); if(!r.ok) throw new Error(r.error||"Không thể tải dữ liệu."); dataset=r.students; render(); }
  function render(){
    const q=$("search").value.trim().toLowerCase(), c=$("classFilter").value, s=$("statusFilter").value;
    const list=dataset.filter(x=>(!q||x.fullName.toLowerCase().includes(q))&&(!c||x.className===c)&&(!s||(s==="done"?x.completed:!x.completed)));
    const rows=$("rows"); rows.innerHTML=list.map(x=>{const subjects=[x.subject1,x.subject2,x.subject3,x.subject4,x.subject5,x.subject6,x.subject7].filter(Boolean).join(", "); const url=`${location.origin}${location.pathname.replace(/admin\.html$/i,'')}?id=${encodeURIComponent(x.token)}`; return `<tr><td><strong>${esc(x.fullName)}</strong></td><td>${esc(x.className||"")}</td><td>${esc(x.email||"")}</td><td>${esc(x.phone||"")}</td><td>${esc(subjects)}</td><td><span class="pill ${x.completed?'good':'pending'}">${x.completed?'Đã hoàn thành':'Chưa hoàn thành'}</span></td><td><button class="copy" data-url="${esc(url)}">Copy link</button></td></tr>`}).join("");
    rows.querySelectorAll("button.copy").forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.url); b.textContent="Đã copy"; setTimeout(()=>b.textContent="Copy link",1200)});
    const total=dataset.length, done=dataset.filter(x=>x.completed).length; $("total").textContent=total; $("done").textContent=done; $("pending").textContent=total-done; $("progress").textContent=total?`${Math.round(done*100/total)}%`:"0%";
  }
  function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
  function login(){ secret=$("password").value.trim(); if(!secret)return; post({action:"adminCheck",secret}).then(r=>{if(!r.ok) throw new Error(r.error||"Sai mật khẩu"); $("login").classList.add("hidden"); $("admin").classList.remove("hidden"); $("logout").classList.remove("hidden"); load().catch(e=>msg(e.message,"error"));}).catch(e=>{$("loginMsg").textContent=e.message; $("loginMsg").className="msg error"}) }
  $("loginForm").onsubmit=e=>{e.preventDefault();login()}; $("logout").onclick=()=>location.reload(); $("refresh").onclick=()=>load().catch(e=>msg(e.message,"error")); ["search","classFilter","statusFilter"].forEach(id=>$(id).addEventListener("input",render));
  $("export").onclick=async()=>{try{msg("Đang tạo file Excel…"); const r=await post({action:"exportExcel",secret}); if(!r.ok)throw new Error(r.error||"Không thể xuất file."); const bin=atob(r.base64), bytes=new Uint8Array(bin.length); for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i); const blob=new Blob([bytes],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download=r.filename||"THPT_Bac_Yen.xlsx"; a.click(); URL.revokeObjectURL(a.href); msg("Xuất Excel thành công.","ok");}catch(e){msg(e.message,"error")}};
  $("importFile").onchange=async e=>{ const f=e.target.files[0]; if(!f)return; try{msg("Đang đọc file Excel…"); const buf=await f.arrayBuffer(); const wb=XLSX.read(buf,{type:"array",cellDates:true}); const ws=wb.Sheets[wb.SheetNames[0]]; const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:""}); const headers=rows[7]||[]; const data=rows.slice(8).filter(r=>r[0]); const payload=data.map(r=>({fullName:r[0],email:r[1],birthDate:r[2],gender:r[3],grade:r[4],address:r[5],phone:r[6],className:r[7],subject1:r[8]==="x"?"x":"",subject2:r[9]==="x"?"x":"",subject3:r[10]==="x"?"x":"",subject4:r[11]==="x"?"x":"",subject5:r[12]==="x"?"x":"",subject6:r[13]==="x"?"x":"",subject7:r[14]==="x"?"x":""})); const out=await post({action:"importStudents",secret,students:payload}); if(!out.ok)throw new Error(out.error||"Không thể nhập dữ liệu."); msg(`Đã nhập ${out.count} học sinh.`,"ok"); await load();}catch(err){msg(err.message,"error")}finally{e.target.value=""} };
  const classFilter=$("classFilter");
  // Populate classes once data exists.
  const oldRender=render; render=()=>{const cls=[...new Set(dataset.map(x=>x.className).filter(Boolean))].sort(); const cur=classFilter.value; classFilter.innerHTML='<option value="">Tất cả lớp</option>'+cls.map(c=>`<option>${esc(c)}</option>`).join(""); if(cls.includes(cur))classFilter.value=cur; oldRender()};
})();
