(() => {
  const api=(window.APP_CONFIG||{}).API_URL||''; const $=id=>document.getElementById(id);
  const token=new URLSearchParams(location.search).get('id'); let currentStudent=null; let requestSeq=0;
  const labels={fullName:{label:'Họ và tên',type:'text',required:true},email:{label:'Email',type:'email',placeholder:'ten@example.com',required:true},birthDate:{label:'Ngày sinh',type:'text',placeholder:'dd/mm/yyyy',required:true},gender:{label:'Giới tính',type:'select',options:['Nam','Nữ'],required:true},grade:{label:'Khối lớp',type:'text',required:true},address:{label:'Địa chỉ',type:'textarea',placeholder:'Bản, xã…',required:true},phone:{label:'Số điện thoại',type:'tel',placeholder:'09xxxxxxxx',required:false},className:{label:'Tên lớp',type:'text',required:true}};
  const subjects=['Toán','Tiếng Anh','Vật lí','Hóa học','Sinh học','Lịch sử','Địa lý']; const keys=subjects.map((_,i)=>`subject${i+1}`);
  function setView(name){['loading','error','studentApp'].forEach(id=>$(id).classList.toggle('hidden',id!==name));}
  function showError(m){$('errorText').textContent=m;setView('error');}
  function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('thpt_theme',theme);$('themeIcon').textContent=theme==='dark'?'☀':'☾';$('themeText').textContent=theme==='dark'?'Sáng':'Tối';}
  $('themeToggle').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'); setTheme(localStorage.getItem('thpt_theme')||'light');
  async function request(url,options={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch(url,{...options,signal:controller.signal,cache:'no-store'});const text=await r.text();if(!text.trim())throw new Error('Máy chủ không trả dữ liệu.');let data;try{data=JSON.parse(text);}catch{throw new Error('Máy chủ trả về dữ liệu không hợp lệ. Hãy kiểm tra URL Web App và quyền truy cập.');}if(!data.ok)throw new Error(data.error||'Máy chủ báo lỗi.');return data;}catch(e){if(e.name==='AbortError')throw new Error('Kết nối quá chậm. Vui lòng thử lại.');throw e;}finally{clearTimeout(timer);}}
  async function getStudent(){const u=new URL(api);u.searchParams.set('action','getStudent');u.searchParams.set('id',token);return request(u.toString());}
  function v(k){return currentStudent?.[k]??'';}
  function render(student){currentStudent=student;$('studentName').textContent=student.fullName||'';$('studentClass').textContent=`Lớp ${student.className||''}${student.grade?' · Khối '+student.grade:''}`;const done=!!student.completed;$('statusBadge').textContent=done?'Đã hoàn thành':'Chưa hoàn thành';$('statusBadge').className=`status ${done?'done':'pending'}`;
    const root=$('fields');root.innerHTML='';const fields=[...new Set([...(student.formFields||student.missingFields||[]),'phone'])];fields.forEach(key=>{const meta=labels[key];if(!meta)return;const wrap=document.createElement('div');wrap.className='field';const lab=document.createElement('label');lab.innerHTML=`${meta.label}${meta.required?' <span class="required-star">*</span>':''}`;wrap.appendChild(lab);let el;if(meta.type==='select'){el=document.createElement('select');el.innerHTML='<option value="">Chọn…</option>'+meta.options.map(x=>`<option>${x}</option>`).join('');el.value=v(key)}else if(meta.type==='textarea'){el=document.createElement('textarea');el.rows=3;el.placeholder=meta.placeholder||'';el.value=v(key)}else{el=document.createElement('input');el.type=meta.type;el.placeholder=meta.placeholder||'';el.value=v(key)}el.name=key;if(meta.required)el.required=true;el.addEventListener('input',()=>wrap.classList.add('filled'),{passive:true});el.addEventListener('change',()=>wrap.classList.add('filled'));wrap.appendChild(el);root.appendChild(wrap)});
    const sub=$('subjectSection');sub.innerHTML='<div class="section-heading"><div><h3>Môn học đăng ký</h3><p class="hint">Chọn các môn bạn đăng ký. Có thể để trống.</p></div></div>';const grid=document.createElement('div');grid.className='checkbox-grid';subjects.forEach((name,i)=>{const key=keys[i],lab=document.createElement('label');lab.className='check';lab.innerHTML=`<input type="checkbox" name="${key}" value="x"><span>${name}</span>`;lab.querySelector('input').checked=String(student[key]||'').toLowerCase()==='x';grid.appendChild(lab)});sub.appendChild(grid);
    $('emptyState').classList.toggle('hidden',!done);$('submitBtn').querySelector('.btn-label').textContent=done?'CẬP NHẬT THÔNG TIN':'LƯU VÀ HOÀN THÀNH';setView('studentApp');}
  $('studentForm').onsubmit=async e=>{e.preventDefault();const button=$('submitBtn');if(button.disabled)return;button.disabled=true;button.innerHTML='<span class="btn-spinner"></span><span>Đang lưu…</span>';$('formMessage').className='form-message';$('formMessage').textContent='Đang lưu thông tin…';const fd=new FormData(e.currentTarget);const data={};const fields=[...new Set([...(currentStudent.formFields||currentStudent.missingFields||[]),'phone'])];fields.forEach(k=>{if(fd.has(k))data[k]=String(fd.get(k)||'').trim()});keys.forEach(k=>data[k]=fd.get(k)==='x'?'x':'');try{const out=await request(api,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'submitStudent',token,data})});render(out.student);$('formMessage').className='form-message ok';$('formMessage').textContent=out.completed?'✓ Đã lưu thành công. Bạn đã hoàn thành thông tin bắt buộc.':'✓ Đã lưu thành công. Bạn có thể cập nhật tiếp khi cần.';try{localStorage.setItem(`thpt_bac_yen_student_${token}`,JSON.stringify({t:Date.now(),student:out.student}))}catch{} }catch(err){$('formMessage').className='form-message error';$('formMessage').textContent='Không thể lưu: '+err.message;}finally{button.disabled=false;if(currentStudent)button.innerHTML=`<span class="btn-label">${currentStudent.completed?'CẬP NHẬT THÔNG TIN':'LƯU VÀ HOÀN THÀNH'}</span>`}};
  if(!token){showError('Thiếu mã nhận diện học sinh trong đường dẫn.');return;}const cacheKey=`thpt_bac_yen_student_${token}`;let cached=null;try{const x=JSON.parse(localStorage.getItem(cacheKey)||'null');if(x&&Date.now()-x.t<120000)cached=x.student}catch{}if(cached)render(cached);requestSeq++;const seq=requestSeq;getStudent().then(r=>{if(seq!==requestSeq)return;render(r.student);try{localStorage.setItem(cacheKey,JSON.stringify({t:Date.now(),student:r.student}))}catch{}}).catch(e=>{if(!cached)showError(e.message)});
})();
